// ui_react/src/pages/LoginPage.tsx
import { Alert, Button, Card, CardActions, CardContent, Stack, TextField } from "@mui/material";
import Center from "../components/Center";
import { useEffect, useRef, useState } from "react";
import AccountService from "../services/AccountService";
import { useNavigate } from "react-router";


export default function LoginPage() {
    const [isRegister, setIsRegister] = useState(false);
    const [username, setUsername] = useState('');
    const [password, setPassword] = useState('');
    const [errors, setErrors] = useState([] as string[])
    const [loading, setLoading] = useState(false);
    const accountService = useRef(new AccountService());
    const navigate = useNavigate();

     useEffect(() => {
        return () => accountService.current.abort();
      }, []);
 
    async function submit()
    {
        setLoading(true);
        var errors = [];

        try {
            
            if (isRegister)
            {
                if (!username.match(/^[a-z0-9]{3,15}$/))
                    errors.push('Usuário deve ter de 3 a 15 letras e números');

                if (!password.match(/^.{3,15}$/))
                    errors.push('Senha deve ter de 3 a 15 caracteres');

                if (errors.length == 0)
                {
                    if (await accountService.current.checkInUse(username))
                        errors.push('Nome de usuário está em uso');
                    else
                    {
                        await accountService.current.register({username, password});
                        onLoginSuccess();
                    }
                }
            }
            else
            {
                await accountService.current.login({username, password});
                onLoginSuccess();
            }
        }
        catch(error)
        {
            var axError = accountService.current.axiosError(error);
            if (axError?.status == 404)
                errors.push('Login incorreto')
            else
                errors.push('Ocorreu um erro');
        }
        finally
        {
            setErrors(errors);
            setLoading(false);
        }
    }

    function onLoginSuccess()
    {
        navigate('/');
    }

    function toggleRegister()
    {
        if (loading)
            return;

        setIsRegister(previous => !previous);
        setErrors([]);
    }

    return (
        <Center sx={{height: '100vh'}}>
            <Card sx={{width: '360px', maxWidth: '100%'}} >
                <CardContent>
                    <Stack spacing={2}>  
                        <TextField
                            label="Nome de usuário"
                            variant="outlined"
                            value={username}
                            onChange={e => setUsername(e.target.value)}
                        />
                        <TextField
                            label="Senha"
                            variant="outlined"
                            type="password" 
                            value={password}
                            onChange={e => setPassword(e.target.value)}
                        />
                        {
                            errors.length == 0 ? <></> :
                            <Alert variant="outlined" severity="warning">
                                <ul style={{margin: '0'}}>
                                    {
                                        errors.map(e => <li key={e}>{e}</li>)
                                    }
                                </ul>
                            </Alert>
                        }
                        
                        <Button onClick={submit} disabled={loading} variant="contained">
                            { isRegister ? 'Cadastrar' : 'Entrar' }
                        </Button>
                    </Stack>
                </CardContent>
                <CardActions>
                    <Button onClick={toggleRegister} disabled={loading} size="small">
                        { isRegister ? 'Possui conta?' :  'Cadastre-se' }
                    </Button>
                </CardActions>                    
            </Card>                
        </Center>
    );
}

// ui_angular/src/pages/login-page.ts
import { Component } from "@angular/core";
import { commonImports } from "../helpers/common-imports";
import { UpperCasePipe } from "@angular/common";
import { AccountService } from "../services/account-service";
import { MatSnackBar } from "@angular/material/snack-bar";
import { Router } from "@angular/router";
import { snackBarDuration } from "../helpers/constants";
import { HttpErrorResponse } from "@angular/common/http";

@Component({
    selector: 'login-page',
    templateUrl: './login-page.html',
    styleUrl: './login-page.scss',
    imports: [commonImports, UpperCasePipe],
    providers: [AccountService],
})
export class LoginPage
{
    username = '';
    password = '';
    isRegister = false;
    loading = false;
    
    constructor(
        private accountService: AccountService,
        private router: Router,
        private snackBar: MatSnackBar
    ){}

    ngOnDestroy()
    {
        this.accountService.abort();
    }
    
    toggleRegister()
    {
        this.isRegister = !this.isRegister;
    }

    get toggleButtonText() {
        return this.isRegister ? 'Possui conta?' : 'Cadastre-se';
    }

    get submitButtonText() {
        return this.isRegister ? 'Registrar' : 'Entrar';
    }
    
    async submit()
    {
        try
        {
            this.loading = true;
            var {username, password} = this;

            if (this.isRegister)
            {
                await this.validateRegister();
                await this.accountService.register({username, password})
            }
            else
                await this.accountService.login({username, password})
                
            this.router.navigate(['/']);
        }
        catch (error: unknown)
        {
            var message = 'Ocorreu um erro';

            if (typeof error == 'string') {
                message = error;
            }
            else if (error instanceof HttpErrorResponse) {
                if (error.status == 404)
                    message = 'Usuário ou senha incorretos';
            }

            this.snackBar.open(message, '', {duration: snackBarDuration});
        }
        finally
        {
            this.loading = false;
        }
    }

    async validateRegister()
    {
        if (!this.username.match(/^[a-z0-9]{3,15}$/))
            throw 'Usuário deve ter de 3 a 15 letras e números';

        if (!this.password.match(/^.{3,15}$/))
            throw 'Senha deve ter de 3 a 15 caracteres';

        if (await this.accountService.checkInUse(this.username))
            throw 'Nome de usuário está em uso';
    }
}
